class LocalizationService {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appSubtitle': 'Legal help, in your language',
      'sharingNotice':
          'Your information is shared with legal-aid staff for review',
      'chooseLanguageHeader': 'CHOOSE YOUR LANGUAGE',
      'welcomeTitle': 'Welcome to AidRoute',
      'welcomeSub':
          "We'll help you organize what happened so a legal-aid team can understand your situation.",
      'explainSituation': 'Explain your situation',
      'addDocsDates': 'Add documents and important dates',
      'submitReview': 'Submit for human review',
      'startNewCase': 'Start a new case',
      'saveProgressNote': 'You can save your progress and come back later',
      'tellUsTitle': 'Tell us what happened',
      'tellUsStep': 'Step 1 of 4 | Your situation',
      'tellUsHint': 'Use your own words. You do not need to use legal terms.',
      'tellUsPlaceholder':
          'For example: I received a notice from my landlord last week...',
      'addDocument': 'Add a document',
      'addImportantDate': 'Add an important date',
      'continueText': 'Continue',
      'backText': 'Back',
      'reviewCaseTitle': 'Review your intake',
      'reviewCaseHint':
          'Check your answers before sending them to the legal-aid team',
      'readyToSubmit': 'Ready to submit',
      'allSectionsComplete': 'All sections complete',
      'whatHappened': 'What happened',
      'importantDate': 'Important date',
      'documents': 'Documents',
      'priorityMediumTitle': 'Priority: Medium',
      'priorityMediumDesc':
          'This helps staff decide what to review first. It is not a legal decision.',
      'submitForReview': 'Submit for review',
      'edit': 'Edit',
      'yourSituationTitle': 'Your situation',
      'reviewWhatYouShared': 'Review what you shared',
      'answersReadyForRouting': 'Your answers are ready for routing',
      'intakeSignals': 'Intake signals',
      'likelyCategory': 'Likely category',
      'housing': 'Housing',
      'urgency': 'Urgency',
      'needsTimelyReview': 'Needs timely review',
      'usedToRoute': 'Used to help route your request',
      'fromYourDocument': 'From your document',
      'responseDateFound': 'Response date found',
      'checkDateBeforeSending': 'Check this date before sending',
      'beforeYouSend': 'Before you send',
      'preferredLanguage': 'Preferred language',
      'notDeterminedYet': 'Not determined yet',
      'eligibilityPreScreening': 'Eligibility pre-screening',
      'housingIssueIdentified': 'Housing issue identified',
      'incomeInfoReceived': 'Income information received',
      'residencyNeedsConfirmation': 'Residency still needs confirmation',
      'sendForReview': 'Send for review',
      'volunteerLawyers': 'Volunteer lawyers',
      'matchFor': 'Match for',
      'caseSummary': 'Case Summary',
      'specialty': 'Specialty',
      'language': 'Language',
      'available': 'Available',
      'thisWeek': 'This week',
      'bestMatches': 'Best matches',
      'whyTheseMatches': 'Why these matches',
      'requestAVolunteer': 'Request a volunteer',
      'writeYourAnswerHere': 'Write your answer here',
      'addNoticeOrAgreement': 'Add a notice or agreement',
      'datesAndDocumentDetails': 'We can look for dates and document details',
      'intakeDisclaimer': 'This is an intake conversation, not legal advice.',
      'start': 'Start',
      'myCase': 'My case',
      'cases': 'Cases',
      'lawyers': 'Lawyers',
      'schedule': 'Schedule',
      'scheduleConsultation': 'Schedule Consultation',
      'selectConsultationMode': 'Select Consultation Mode',
      'scheduleCall': 'Schedule Call',
      'inPersonVisit': 'In-Person Visit',
      'selectDate': 'Select Date',
      'availableTimeSlots': 'Available Time Slots',
      'confirmAppointmentSlot': 'Confirm Appointment Slot',
      'proceedToTriage': 'Proceed to Triage Assessment',
      'reviewCaseSummary': 'Review Case Summary',
      'continueToEligibility': 'Continue to Eligibility Pre-Screening',
    },
    'es': {
      'appSubtitle': 'Ayuda legal, en su idioma',
      'sharingNotice':
          'Su información se comparte con el personal de asistencia legal para su revisión',
      'chooseLanguageHeader': 'ELIJA SU IDIOMA',
      'welcomeTitle': 'Bienvenido a AidRoute',
      'welcomeSub':
          'Le ayudaremos a organizar lo sucedido para que el equipo de asistencia legal entienda su situación.',
      'explainSituation': 'Explique su situación',
      'addDocsDates': 'Agregar documentos y fechas importantes',
      'submitReview': 'Enviar para revisión humana',
      'startNewCase': 'Iniciar un nuevo caso',
      'saveProgressNote': 'Puede guardar su progreso y volver más tarde',
      'tellUsTitle': 'Cuéntenos qué sucedió',
      'tellUsStep': 'Paso 1 de 4 | Su situación',
      'tellUsHint':
          'Use sus propias palabras. No necesita usar términos legales.',
      'tellUsPlaceholder':
          'Por ejemplo: Recibí un aviso de mi arrendador la semana pasada...',
      'addDocument': 'Agregar un documento',
      'addImportantDate': 'Agregar fecha importante',
      'continueText': 'Continuar',
      'backText': 'Atrás',
      'reviewCaseTitle': 'Revisar su admisión',
      'reviewCaseHint':
          'Verifique sus respuestas antes de enviarlas al equipo legal',
      'readyToSubmit': 'Listo para enviar',
      'allSectionsComplete': 'Todas las secciones completas',
      'whatHappened': 'Qué sucedió',
      'importantDate': 'Fecha importante',
      'documents': 'Documentos',
      'priorityMediumTitle': 'Prioridad: Media',
      'priorityMediumDesc': 'Ayuda al personal a priorizar la revisión.',
      'submitForReview': 'Enviar para revisión',
      'edit': 'Editar',
      'yourSituationTitle': 'Su situación',
      'reviewWhatYouShared': 'Revise lo que compartió',
      'answersReadyForRouting': 'Sus respuestas están listas para enrutamiento',
      'intakeSignals': 'Señales de admisión',
      'likelyCategory': 'Categoría probable',
      'housing': 'Vivienda',
      'urgency': 'Urgencia',
      'needsTimelyReview': 'Requiere revisión oportuna',
      'usedToRoute': 'Utilizado para ayudar a enrutar su solicitud',
      'fromYourDocument': 'De su documento',
      'responseDateFound': 'Fecha de respuesta encontrada',
      'checkDateBeforeSending': 'Verifique esta fecha antes de enviar',
      'beforeYouSend': 'Antes de enviar',
      'preferredLanguage': 'Idioma preferido',
      'eligibilityPreScreening': 'Preselección de elegibilidad',
      'housingIssueIdentified': 'Problema de vivienda identificado',
      'incomeInfoReceived': 'Información de ingresos recibida',
      'residencyNeedsConfirmation': 'La residencia aún necesita confirmación',
      'sendForReview': 'Enviar para revisión',
      'volunteerLawyers': 'Abogados voluntarios',
      'matchFor': 'Coincidencia para',
      'specialty': 'Especialidad',
      'language': 'Idioma',
      'available': 'Disponible',
      'thisWeek': 'Esta semana',
      'bestMatches': 'Mejores coincidencias',
      'whyTheseMatches': 'Por qué estas coincidencias',
      'requestAVolunteer': 'Solicitar un voluntario',
      'writeYourAnswerHere': 'Escriba su respuesta aquí',
      'addNoticeOrAgreement': 'Agregar un aviso o acuerdo',
      'datesAndDocumentDetails':
          'Podemos buscar fechas y detalles del documento',
      'intakeDisclaimer':
          'Esta es una conversación de admisión, no asesoramiento legal.',
      'start': 'Inicio',
      'myCase': 'Mi caso',
      'cases': 'Casos',
      'lawyers': 'Abogados',
      'schedule': 'Agenda',
      'scheduleConsultation': 'Programar consulta',
      'selectConsultationMode': 'Seleccionar modo de consulta',
      'scheduleCall': 'Programar llamada',
      'inPersonVisit': 'Visita en persona',
      'selectDate': 'Seleccionar fecha',
      'availableTimeSlots': 'Horarios disponibles',
      'confirmAppointmentSlot': 'Confirmar horario de cita',
      'proceedToTriage': 'Proceder a la evaluación de triaje',
      'reviewCaseSummary': 'Revisar resumen del caso',
      'continueToEligibility': 'Continuar a la preselección de elegibilidad',
    },
    'fr': {
      'appSubtitle': 'Aide juridique, dans votre langue',
      'sharingNotice':
          'Vos informations sont partagées avec l’équipe d’aide juridique pour examen',
      'chooseLanguageHeader': 'CHOISISSEZ VOTRE LANGUE',
      'welcomeTitle': 'Bienvenue sur AidRoute',
      'welcomeSub':
          'Nous vous aiderons à organiser les faits pour que l’équipe juridique comprenne votre situation.',
      'explainSituation': 'Expliquez votre situation',
      'addDocsDates': 'Ajouter des documents et dates importantes',
      'submitReview': 'Soumettre pour examen humain',
      'startNewCase': 'Commencer un nouveau dossier',
      'saveProgressNote':
          'Vous pouvez enregistrer votre progression et revenir plus tard',
      'tellUsTitle': 'Racontez-nous ce qui s’est passé',
      'tellUsStep': 'Étape 1 sur 4 | Votre situation',
      'tellUsHint':
          'Utilisez vos propres mots. Pas besoin de termes juridiques.',
      'tellUsPlaceholder':
          'Exemple: J’ai reçu un avis de mon propriétaire la semaine dernière...',
      'addDocument': 'Ajouter un document',
      'addImportantDate': 'Ajouter une date importante',
      'continueText': 'Continuer',
      'backText': 'Retour',
      'reviewCaseTitle': 'Vérifier votre orientation',
      'reviewCaseHint': 'Vérifiez vos réponses avant de les envoyer',
      'readyToSubmit': 'Prêt à soumettre',
      'allSectionsComplete': 'Toutes les sections sont complètes',
      'whatHappened': 'Ce qui s’est passé',
      'importantDate': 'Date importante',
      'documents': 'Documents',
      'priorityMediumTitle': 'Priorité: Moyenne',
      'priorityMediumDesc': 'Aide le personnel à prioriser l’examen.',
      'submitForReview': 'Soumettre pour examen',
      'edit': 'Modifier',
      'yourSituationTitle': 'Votre situation',
      'reviewWhatYouShared': 'Consultez ce que vous avez partagé',
      'answersReadyForRouting': 'Vos réponses sont prêtes pour l’orientation',
      'intakeSignals': 'Signaux d’orientation',
      'likelyCategory': 'Catégorie probable',
      'housing': 'Logement',
      'urgency': 'Urgence',
      'needsTimelyReview': 'Examen opportun requis',
      'usedToRoute': 'Utilisé pour guider votre demande',
      'fromYourDocument': 'Extrait de votre document',
      'responseDateFound': 'Date de réponse trouvée',
      'checkDateBeforeSending': 'Vérifiez cette date avant d’envoyer',
      'beforeYouSend': 'Avant d’envoyer',
      'preferredLanguage': 'Langue préférée',
      'eligibilityPreScreening': 'Pré-évaluation d’éligibilité',
      'housingIssueIdentified': 'Problème de logement identifié',
      'incomeInfoReceived': 'Informations sur le revenu reçues',
      'residencyNeedsConfirmation': 'La résidence nécessite une confirmation',
      'sendForReview': 'Envoyer pour examen',
      'volunteerLawyers': 'Avocats bénévoles',
      'matchFor': 'Correspondance pour',
      'specialty': 'Spécialité',
      'language': 'Langue',
      'available': 'Disponible',
      'thisWeek': 'Cette semaine',
      'bestMatches': 'Meilleures correspondances',
      'whyTheseMatches': 'Pourquoi ces correspondances',
      'requestAVolunteer': 'Demander un bénévole',
      'writeYourAnswerHere': 'Écrivez votre réponse ici',
      'addNoticeOrAgreement': 'Ajouter un avis ou un accord',
      'datesAndDocumentDetails': 'Nous pouvons rechercher des dates et détails',
      'intakeDisclaimer':
          'Ceci est une conversation d’orientation, pas un conseil juridique.',
      'start': 'Accueil',
      'myCase': 'Mon dossier',
      'cases': 'Dossiers',
      'lawyers': 'Avocats',
      'schedule': 'Planning',
      'scheduleConsultation': 'Planifier une consultation',
      'selectConsultationMode': 'Choisir le mode de consultation',
      'scheduleCall': 'Planifier un appel',
      'inPersonVisit': 'Visite en personne',
      'selectDate': 'Sélectionner une date',
      'availableTimeSlots': 'Créneaux horaires disponibles',
      'confirmAppointmentSlot': 'Confirmer le créneau de rendez-vous',
      'proceedToTriage': 'Procéder à l’évaluation de triage',
      'reviewCaseSummary': 'Examiner le résumé du dossier',
      'continueToEligibility': 'Continuer vers la pré-évaluation d’éligibilité',
    },
    'hi': {
      'appSubtitle': 'आपकी भाषा में कानूनी सहायता',
      'sharingNotice':
          'आपकी जानकारी समीक्षा के लिए कानूनी सहायता टीम को भेजी जाती है',
      'chooseLanguageHeader': 'भाषा चुनें / CHOOSE YOUR LANGUAGE',
      'welcomeTitle': 'AidRoute में आपका स्वागत है',
      'welcomeSub':
          'हम आपकी समस्या को व्यवस्थित करने में मदद करेंगे ताकि कानूनी टीम इसे समझ सके।',
      'explainSituation': 'अपनी स्थिति समझाएं',
      'addDocsDates': 'दस्तावेज़ और महत्वपूर्ण तारीखें जोड़ें',
      'submitReview': 'समीक्षा के लिए भेजें',
      'startNewCase': 'नया मामला दर्ज करें',
      'saveProgressNote':
          'आप अपनी प्रगति सहेज सकते हैं और बाद में वापस आ सकते हैं',
      'tellUsTitle': 'बताएं क्या हुआ था',
      'tellUsStep': 'चरण 1 का 4 | आपकी स्थिति',
      'tellUsHint':
          'अपने शब्दों का प्रयोग करें। कानूनी शब्दों की आवश्यकता नहीं है।',
      'tellUsPlaceholder':
          'उदाहरण के लिए: मुझे पिछले हफ्ते मकान मालिक से नोटिस मिला...',
      'addDocument': 'दस्तावेज़ जोड़ें',
      'addImportantDate': 'महत्वपूर्ण तारीख जोड़ें',
      'continueText': 'आगे बढ़ें',
      'backText': 'पीछे',
      'reviewCaseTitle': 'मामले की समीक्षा करें',
      'reviewCaseHint': 'लीगल टीम को भेजने से पहले अपने उत्तर जांच लें',
      'readyToSubmit': 'जमा करने के लिए तैयार',
      'allSectionsComplete': 'सभी अनुभाग पूरे हैं',
      'whatHappened': 'क्या हुआ था',
      'importantDate': 'महत्वपूर्ण तारीख',
      'documents': 'दस्तावेज़',
      'priorityMediumTitle': 'प्राथमिकता: मध्यम',
      'priorityMediumDesc':
          'इससे टीम को समीक्षा का क्रम तय करने में मदद मिलती है।',
      'submitForReview': 'समीक्षा के लिए जमा करें',
      'edit': 'संशोधन',
      'yourSituationTitle': 'आपकी स्थिति',
      'reviewWhatYouShared': 'आपके द्वारा दी गई जानकारी की समीक्षा करें',
      'answersReadyForRouting': 'आपके उत्तर रूटिंग के लिए तैयार हैं',
      'intakeSignals': 'इंटेक संकेत',
      'likelyCategory': 'संभावित श्रेणी',
      'housing': 'आवास (Housing)',
      'urgency': 'उरगेन्सी / प्राथमिकता',
      'needsTimelyReview': 'समय पर समीक्षा की आवश्यकता',
      'usedToRoute': 'अनुरोध को रूट करने में मदद करता है',
      'fromYourDocument': 'दस्तावेज़ से',
      'responseDateFound': 'प्रतिक्रिया तिथि मिली',
      'checkDateBeforeSending': 'भेजने से पहले तिथि जांचें',
      'beforeYouSend': 'भेजने से पहले',
      'preferredLanguage': 'पसंदीदा भाषा',
      'notDeterminedYet': 'अभी तय नहीं हुआ',
      'eligibilityPreScreening': 'पात्रता पूर्व-स्क्रीनिंग',
      'housingIssueIdentified': 'आवास की समस्या पहचानी गई',
      'incomeInfoReceived': 'आय की जानकारी प्राप्त हुई',
      'residencyNeedsConfirmation': 'निवास की अभी पुष्टि आवश्यक है',
      'sendForReview': 'समीक्षा के लिए भेजें',
      'volunteerLawyers': 'स्वयंसेवक वकील',
      'matchFor': 'मैच केस',
      'caseSummary': 'केस सारांश',
      'specialty': 'विशेषज्ञता',
      'language': 'भाषा',
      'available': 'उपलब्ध',
      'thisWeek': 'इस सप्ताह',
      'bestMatches': 'सर्वश्रेष्ठ वकील मैच',
      'whyTheseMatches': 'ये मैच क्यों चुन गए',
      'requestAVolunteer': 'स्वयंसेवक का अनुरोध करें',
      'writeYourAnswerHere': 'अपना उत्तर यहाँ लिखें',
      'addNoticeOrAgreement': 'नोटिस या समझौता जोड़ें',
      'datesAndDocumentDetails': 'हम तारीखें और विवरण ढूंढ सकते हैं',
      'intakeDisclaimer': 'यह एक इंटेक बातचीत है, कानूनी सलाह नहीं।',
      'start': 'प्रारंभ',
      'myCase': 'मेरा मामला',
      'cases': 'मामले',
      'lawyers': 'वकील',
      'schedule': 'अनुसूची',
      'scheduleConsultation': 'परामर्श का समय निर्धारित करें',
      'selectConsultationMode': 'परामर्श मोड चुनें',
      'scheduleCall': 'कॉल शेड्यूल करें',
      'inPersonVisit': 'व्यक्तिगत मुलाकात',
      'selectDate': 'तारीख चुनें',
      'availableTimeSlots': 'उपलब्ध समय स्लॉट',
      'confirmAppointmentSlot': 'अपॉइंटमेंट स्लॉट की पुष्टि करें',
      'proceedToTriage': 'ट्रियाज मूल्यांकन के लिए आगे बढ़ें',
      'reviewCaseSummary': 'मामले का सारांश देखें',
      'continueToEligibility': 'पात्रता पूर्व-जांच के लिए आगे बढ़ें',
    },
    'mr': {
      'appSubtitle': 'तुमच्या भाषेत कायदेशीर मदत',
      'sharingNotice':
          'तुमची माहिती पुनरावलोकनासाठी कायदेशीर मदत टीमसोबत शेअर केली जाते',
      'chooseLanguageHeader': 'भाषा निवडा / CHOOSE LANGUAGE',
      'welcomeTitle': 'AidRoute मध्ये आपले स्वागत आहे',
      'welcomeSub':
          'कायदेशीर टीमला तुमची परिस्थिती समजण्यास मदत व्हावी म्हणून आम्ही माहिती व्यवस्थित करतो.',
      'explainSituation': 'तुमची परिस्थिती सांगा',
      'addDocsDates': 'कागदपत्रे आणि महत्त्वाच्या तारखा जोडा',
      'submitReview': 'समीक्षेसाठी सादर करा',
      'startNewCase': 'नवीन केस सुरू करा',
      'saveProgressNote': 'तुम्ही प्रगती सेव्ह करू शकता आणि नंतर परत येऊ शकता',
      'tellUsTitle': 'काय घडले ते सांगा',
      'tellUsStep': 'पायरी 1 पैकी 4 | तुमची परिस्थिती',
      'tellUsHint':
          'तुमचे स्वतःचे शब्द वापरा. कायदेशीर शब्द वापरण्याची गरज नाही.',
      'tellUsPlaceholder':
          'उदाहरणार्थ: मला गेल्या आठवड्यात घरमालकाकडून नोटीस मिळाली...',
      'addDocument': 'कागदपत्र जोडा',
      'addImportantDate': 'महत्त्वाची तारीख जोडा',
      'continueText': 'पुढे जा',
      'backText': 'मागे',
      'reviewCaseTitle': 'तुमच्या केसचे पुनरावलोकन करा',
      'reviewCaseHint': 'कायदेशीर मदत टीमला पाठवण्यापूर्वी तुमची उत्तरे तपासा',
      'readyToSubmit': 'सबमिट करण्यासाठी तयार',
      'allSectionsComplete': 'सर्व विभाग पूर्ण झाले आहेत',
      'whatHappened': 'काय घडले',
      'importantDate': 'महत्त्वाची तारीख',
      'documents': 'कागदपत्रे',
      'priorityMediumTitle': 'प्राधान्य: मध्यम',
      'priorityMediumDesc':
          'यामुळे टीमला आधी कशाचे पुनरावलोकन करायचे ते ठरवण्यात मदत होते.',
      'submitForReview': 'समीक्षेसाठी सबमिट करा',
      'edit': 'संपादन करा',
      'yourSituationTitle': 'तुमची परिस्थिती',
      'reviewWhatYouShared': 'तुम्ही शेअर केलेल्या माहितीचे पुनरावलोकन करा',
      'answersReadyForRouting': 'तुमची उत्तरे पुढच्या प्रक्रियेसाठी तयार आहेत',
      'intakeSignals': 'इंटेक संकेत',
      'likelyCategory': 'संभाव्य वर्ग',
      'housing': 'गृहनिर्माण (Housing)',
      'urgency': 'तातडीची गरज',
      'needsTimelyReview': 'वेळेवर पुनरावलोकन आवश्यक',
      'usedToRoute': 'केस योग्य मार्गदर्शनासाठी वापरले जाते',
      'fromYourDocument': 'तुमच्या कागदपत्रावरून',
      'responseDateFound': 'प्रतिसादाची तारीख सापडली',
      'checkDateBeforeSending': 'पाठवण्यापूर्वी ही तारीख तपासा',
      'beforeYouSend': 'पाठवण्यापूर्वी',
      'preferredLanguage': 'पसंतीची भाषा',
      'eligibilityPreScreening': 'पात्रता पूर्व-तपासणी',
      'housingIssueIdentified': 'गृहनिर्माण अडचण ओळखली',
      'incomeInfoReceived': 'उत्पन्नाची माहिती मिळाली',
      'residencyNeedsConfirmation': 'रहिवासी पुष्टी अद्याप बाकी आहे',
      'sendForReview': 'समीक्षेसाठी पाठवा',
      'volunteerLawyers': 'स्वयंसेवक वकील',
      'matchFor': 'केस मॅच',
      'specialty': 'विशेषज्ज्ञता',
      'language': 'भाषा',
      'available': 'उपलब्ध',
      'thisWeek': 'या आठवड्यात',
      'bestMatches': 'सर्वोत्तम वकील मॅच',
      'whyTheseMatches': 'हेच वकील का निवडले',
      'requestAVolunteer': 'स्वयंसेवकाची विनंती करा',
      'writeYourAnswerHere': 'तुमचे उत्तर येथे लिहा',
      'addNoticeOrAgreement': 'नोटीस किंवा करार जोडा',
      'datesAndDocumentDetails': 'आम्ही तारखा आणि माहिती शोधू शकतो',
      'intakeDisclaimer':
          'हा फक्त माहिती संकलन संवाद आहे, कायदेशीर सल्ला नाही.',
      'start': 'शुरू',
      'myCase': 'माझी केस',
      'cases': 'केसेस',
      'lawyers': 'वकील',
      'schedule': 'वेळापत्रक',
      'scheduleConsultation': 'सल्लामसलत वेळ निश्चित करा',
      'selectConsultationMode': 'सल्लामसलत पद्धत निवडा',
      'scheduleCall': 'कॉल शेड्यूल करा',
      'inPersonVisit': 'प्रत्यक्ष भेट',
      'selectDate': 'तारीख निवडा',
      'availableTimeSlots': 'उपलब्ध वेळ स्लॉट',
      'confirmAppointmentSlot': 'अपॉइंटमेंट स्लॉटची पुष्टी करा',
      'proceedToTriage': 'ट्रियाज मूल्यांकनासाठी पुढे जा',
      'reviewCaseSummary': 'केसचा सारांश तपासा',
      'continueToEligibility': 'पात्रता पूर्व-तपासणीसाठी पुढे जा',
    },
    'mix': {
      'appSubtitle': 'Legal help in English, Hindi & Marathi Mix',
      'sharingNotice':
          'Your data legal-aid staff ke review ke liye submit hoga',
      'chooseLanguageHeader': 'CHOOSE LANGUAGE MODE',
      'welcomeTitle': 'Welcome to AidRoute',
      'welcomeSub':
          "We'll help you simple language mein case prepare karne me so legal team easily samjh sake.",
      'explainSituation': 'Explain your situation',
      'addDocsDates': 'Add documents and important dates',
      'submitReview': 'Submit for review',
      'startNewCase': 'Start a new case',
      'saveProgressNote': 'You can save your progress & resume anytime',
      'tellUsTitle': 'Tell us what happened',
      'tellUsStep': 'Step 1 of 4 | Your situation',
      'tellUsHint':
          'Use your own words. Legal terms use karne ki zaroorat nahi hai.',
      'tellUsPlaceholder':
          'Example: Landlord se notice mila, pay stub document hai...',
      'addDocument': 'Add a document',
      'addImportantDate': 'Add an important date',
      'continueText': 'Continue',
      'backText': 'Back',
      'reviewCaseTitle': 'Review your intake',
      'reviewCaseHint': 'Send karne se pehle apni detail check karein',
      'readyToSubmit': 'Ready to submit',
      'allSectionsComplete': 'All sections complete',
      'whatHappened': 'What happened',
      'importantDate': 'Important date',
      'documents': 'Documents attached',
      'priorityMediumTitle': 'Priority: Medium',
      'priorityMediumDesc': 'Helps staff prioritize review.',
      'submitForReview': 'Submit for review',
      'edit': 'Edit',
      'yourSituationTitle': 'Your situation',
      'reviewWhatYouShared': 'Review what you shared',
      'answersReadyForRouting': 'Your answers are ready for routing',
      'intakeSignals': 'Intake signals',
      'likelyCategory': 'Likely category',
      'housing': 'Housing',
      'urgency': 'Urgency',
      'needsTimelyReview': 'Needs timely review',
      'usedToRoute': 'Used to help route your request',
      'fromYourDocument': 'From your document',
      'responseDateFound': 'Response date found',
      'checkDateBeforeSending': 'Check this date before sending',
      'beforeYouSend': 'Before you send',
      'preferredLanguage': 'Preferred language',
      'eligibilityPreScreening': 'Eligibility pre-screening',
      'housingIssueIdentified': 'Housing issue identified',
      'incomeInfoReceived': 'Income information received',
      'residencyNeedsConfirmation': 'Residency still needs confirmation',
      'sendForReview': 'Send for review',
      'volunteerLawyers': 'Volunteer lawyers',
      'matchFor': 'Match for',
      'specialty': 'Specialty',
      'language': 'Language',
      'available': 'Available',
      'thisWeek': 'This week',
      'bestMatches': 'Best matches',
      'whyTheseMatches': 'Why these matches',
      'requestAVolunteer': 'Request a volunteer',
      'writeYourAnswerHere': 'Write your answer here',
      'addNoticeOrAgreement': 'Add a notice or agreement',
      'datesAndDocumentDetails': 'We can look for dates and document details',
      'intakeDisclaimer': 'This is an intake conversation, not legal advice.',
      'start': 'Start',
      'myCase': 'My case',
      'cases': 'Cases',
      'lawyers': 'Lawyers',
      'schedule': 'Schedule',
      'scheduleConsultation': 'Schedule Consultation',
      'selectConsultationMode': 'Select Consultation Mode',
      'scheduleCall': 'Schedule Call',
      'inPersonVisit': 'In-Person Visit',
      'selectDate': 'Select Date',
      'availableTimeSlots': 'Available Time Slots',
      'confirmAppointmentSlot': 'Confirm Appointment Slot',
      'proceedToTriage': 'Proceed to Triage Assessment',
      'reviewCaseSummary': 'Review Case Summary',
      'continueToEligibility': 'Continue to Eligibility Pre-Screening',
    },
  };

  static String getText(String languageCode, String key) {
    final langValues =
        _localizedValues[languageCode] ?? _localizedValues['en']!;
    return langValues[key] ?? _localizedValues['en']![key] ?? key;
  }
}
